const data = {
  products: [
    {
      name: 'Buttoned shirt with stripes',
      slug: 'stripe-buttoned-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 129,
      size: 'L',
      gender: 'Men',
      countInStock: 10,
      brand: 'LOUIS VUITTON',
      rating: 4.5,
      numReviews: 10,
      description:
        'A shirt is a piece of clothing that you wear on the upper part of your body. Shirts have a collar, sleeves, and buttons down the front.',
    },
    {
      name: 'Buttoned shirt with flowers',
      slug: 'flower-buttoned-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 139,
      size: 'XL',
      gender: 'Men',
      countInStock: 15,
      brand: 'LOUIS VUITTON',
      rating: 5,
      numReviews: 11,
      description:
        'A shirt is a piece of clothing that you wear on the upper part of your body. Shirts have a collar, sleeves, and buttons down the front.',
    },
    {
      name: 'Black Buttoned shirt with stripes',
      slug: 'black-stripe-buttoned-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 179,
      size: 'L',
      gender: 'Women',
      countInStock: 12,
      brand: 'LOUIS VUITTON',
      rating: 5,
      numReviews: 17,
      description:
        'A shirt is a piece of clothing that you wear on the upper part of your body. Shirts have a collar, sleeves, and buttons down the front.',
    },
    {
      name: 'Black shirt with stripes',
      slug: 'black-buttoned-shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 169,
      size: 'L',
      gender: 'Men',
      countInStock: 12,
      brand: 'GUCCI',
      rating: 5,
      numReviews: 21,
      description:
        'A shirt is a piece of clothing that you wear on the upper part of your body. Shirts have a collar, sleeves, and buttons down the front.',
    },
    {
      name: 'Desert jacket',
      slug: 'desert-jacket',
      category: 'Jacket',
      image: '/images/p5.jpg',
      price: 279,
      size: 'L',
      gender: 'Men',
      countInStock: 15,
      brand: 'FENDI',
      rating: 3.5,
      numReviews: 11,
      description: 'A jacket is a short coat with long sleeves.',
    },
    {
      name: 'Buttoned shirt with squares',
      slug: 'squares-buttoned-shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 149,
      size: 'M',
      gender: 'Men',
      countInStock: 12,
      brand: 'LOUIS VUITTON',
      rating: 5,
      numReviews: 15,
      description:
        'A shirt is a piece of clothing that you wear on the upper part of your body. Shirts have a collar, sleeves, and buttons down the front.',
    },
  ],
};

export default data;
