const data = {
  products: [
    {
      name: 'Hermès - Bracelet',
      slug: 'Hermès-bracelet',
      category: 'Bracelet',
      image: '/images/p1.jpg',
      price: 200,
      size: 'One size',
      material: 'Enamel, Metal',
      height: '6.5cm',
      width: '1cm',
      colour: 'Gold,Green',
      totalweight: '26.9',
      gender: 'Women',
      condition: 'Good condition, used with some signs of wear',
      countInStock: 0,
      brand: 'Hermès',
      rating: 4.5,
      numReviews: 10,
      description:
        'Hermes goldtone enamel bangle bracelet narrow bracelet with ornaments and gold stripes on the sides very good condition inner diameter 6.5 cm material - metal enamel',
    },
    {
      name: 'Hermès - Bracelet',
      slug: 'Hermès-Leather-bracelet',
      category: 'Bracelet',
      image: '/images/p2.jpg',
      price: 140,
      size: 'One size',
      material: 'Leather',
      height: '1 cm',
      width: '38 cm',
      colour: 'Black, Brown, Silver',
      gender: 'Women',
      totalweight: '20.6',
      condition: 'Very good condition, slightly used with small signs of wear',
      countInStock: 1,
      brand: 'Hermès',
      rating: 3,
      numReviews: 7,
      description:
        'Hermes double leather bracelet in a good condition full length 38cm color brown silver real leather material metal',
    },
    {
      name: 'Tiffany - 925 Silver- Bracelet',
      slug: 'Tiffany-silver-bracelet',
      category: 'Bracelet',
      image: '/images/p3.jpg',
      price: 365,
      size: 'One size',
      material: 'Silver',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Black, Brown, Silver',
      gender: 'Women',
      totalweight: '33.7',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 3,
      numReviews: 7,
      description:
        'Tiffany - narrow silver bracelet 1837 in a good condition inner diameter 5.5 cm weight 33.7 gr engraved 1997 Tiffany Co 925',
    },
    {
      name: 'Tiffany - 925 Silver - Bracelet',
      slug: 'Tiffany-Atlas-silver-bracelet',
      category: 'Bracelet',
      image: '/images/p4.jpg',
      price: 200,
      size: 'One size',
      material: 'Silver',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Silver',
      gender: 'Unisex',
      totalweight: '21.6',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany bracelet 925 Silver "Atlas" in a good condition. material silver 925 engraved by Tiffany Co. 1995',
    },
    {
      name: 'Tiffany - Gold - Bracelet',
      slug: 'Tiffany-silver-bracelet-2',
      category: 'Bracelet',
      image: '/images/p5.jpg',
      price: 1940,
      size: 'One size',
      material: 'Gold',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Gold',
      gender: 'Unisex',
      totalweight: '17.7',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany - bracelet with hearts and stars  material gold 750 bracelet length - 17/5 cm weight -17.7 grams In a very good condition',
    },
    {
      name: 'Tiffany - Silver - Bracelet',
      slug: 'Tiffany-bracelet',
      category: 'Bracelet',
      image: '/images/p6.jpg',
      price: 430,
      size: 'One size',
      material: 'Silver',
      height: '3 cm',
      width: '7.5 cm',
      colour: 'silver',
      gender: 'Unisex',
      totalweight: '57.3',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany - bracelet with hearts and stars  material gold 750 bracelet length - 17/5 cm weight -17.7 grams In a very good condition',
    },
  ],
};

export default data;
