import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Hermès - Bracelet',
      slug: 'Hermès-bracelet',
      category: 'Bracelet',
      image: '/images/p1.jpg',
      price: 200,
      size: 'One size',
      material: 'Enamel, Metal',
      height: '6.5 cm',
      width: '1 cm',
      colour: 'Gold, Red',
      totalweight: '26.9',
      gender: 'Women',
      condition: 'Good condition, used with some signs of wear',
      countInStock: 3,
      brand: 'Hermès',
      rating: 4.5,
      numReviews: 10,
      description:
        'Hermes goldtone enamel bangle bracelet narrow bracelet with ornaments and gold stripes on the sides very good condition inner diameter 6.5 cm material - metal enamel',
    },
    {
      //_id: '2',
      name: 'Hermès Bracelet Leather',
      slug: 'Hermès-Leather-bracelet',
      category: 'Bracelet',
      image: '/images/p2.jpg',
      price: 140,
      size: 'One size',
      material: 'Leather',
      height: '1 cm',
      width: '38 cm',
      colour: 'Black, Brown, Silver',
      gender: 'Women',
      totalweight: '20.6',
      condition: 'Very good condition, slightly used with small signs of wear',
      countInStock: 1,
      brand: 'Hermès',
      rating: 3,
      numReviews: 7,
      description:
        'Hermes double leather bracelet in a good condition full length 38cm color brown silver real leather material metal',
    },
    {
      //_id: '3',
      name: 'Tiffany - 925 Silver- Bracelet',
      slug: 'Tiffany-silver-bracelet',
      category: 'Bracelet',
      image: '/images/p3.jpg',
      price: 365,
      size: 'One size',
      material: 'Silver',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Black, Brown, Silver',
      gender: 'Women',
      totalweight: '33.7',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 3,
      numReviews: 7,
      description:
        'Tiffany - narrow silver bracelet 1837 in a good condition inner diameter 5.5 cm weight 33.7 gr engraved 1997 Tiffany Co 925',
    },
    {
      //_id: '4',
      name: 'Tiffany - 925 Silver - Bracelet',
      slug: 'Tiffany-Atlas-silver-bracelet',
      category: 'Bracelet',
      image: '/images/p4.jpg',
      price: 200,
      size: 'One size',
      material: 'Silver',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Silver',
      gender: 'Unisex',
      totalweight: '21.6',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany bracelet 925 Silver "Atlas" in a good condition. material silver 925 engraved by Tiffany Co. 1995',
    },
    {
      //_id: '5',
      name: 'Tiffany - Gold - Bracelet',
      slug: 'Tiffany-silver-bracelet-2',
      category: 'Bracelet',
      image: '/images/p5.jpg',
      price: 1940,
      size: 'One size',
      material: 'Gold',
      height: '2 cm',
      width: '5.5 cm',
      colour: 'Gold',
      gender: 'Unisex',
      totalweight: '17.7',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany - bracelet with hearts and stars  material gold 750 bracelet length - 17/5 cm weight -17.7 grams In a very good condition',
    },
    {
      // _id: '6',
      name: 'Tiffany - Silver - Bracelet',
      slug: 'Tiffany-bracelet',
      category: 'Bracelet',
      image: '/images/p6.jpg',
      price: 430,
      size: 'One size',
      material: 'Silver',
      height: '3 cm',
      width: '7.5 cm',
      colour: 'silver',
      gender: 'Unisex',
      totalweight: '57.3',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 4,
      numReviews: 9,
      description:
        'Tiffany - bracelet with hearts and stars  material gold 750 bracelet length - 17/5 cm weight -17.7 grams In a very good condition',
    },
    {
      // _id: '7',
      name: 'Tiffany Silver, Yellow gold - Necklace',
      slug: 'Tiffany Silver Yellow gold Necklace',
      category: 'Necklace',
      image: '/images/p7.jpg',
      price: 390,
      size: 'One size',
      material: 'silver 925 gold 750',
      height: '44 cm',
      width: '1 cm',
      colour: 'silver and gold',
      gender: 'Unisex',
      totalweight: '48.9 grams',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 2,
      numReviews: 3,
      description:
        'Tiffany - twisted chain. good condition material - silver 925 gold 750 total weight - 48.9 grams total length approx 44 cm',
    },
    {
      // _id: '8',
      name: 'Tiffany - 925 Gold, Silver - Earring',
      slug: 'Tiffany 925 Gold Silver Earring',
      category: 'Earring',
      image: '/images/p8.jpg',
      price: 390,
      size: 'One size',
      material: 'Gold, Silver',
      height: '5 cm',
      width: '3 cm',
      colour: 'silver and gold',
      gender: 'Women',
      totalweight: '9.1 g',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 6,
      numReviews: 8,
      description:
        'Tiffany - clips silver gold 750 in a good condition. there are small scratches. material silver 925 gold 750. engraving available',
    },
    {
      // _id: '8',
      name: 'Tiffany - 925 Silver - Earring',
      slug: 'Tiffany 925 Silver Earring',
      category: 'Earring',
      image: '/images/p9.jpg',
      price: 450,
      size: 'One size',
      material: 'Silver',
      height: '4 cm',
      width: '3 cm',
      colour: 'silver and gold',
      gender: 'Women',
      totalweight: '15.3 g',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Tiffany',
      rating: 1,
      numReviews: 3,
      description:
        'Tiffany - clips silver very rare lapis lazuli earrings release discontinued good condition material - silver 925 natural lapis lazuli',
    },
    {
      // _id: '8',
      name: 'Gucci - 925 Silver - Bracelet',
      slug: 'Gucci 925 Silver Bracelet',
      category: 'Bracelet',
      image: '/images/p10.jpg',
      price: 220,
      size: 'One size',
      material: 'Silver',
      height: '10 cm',
      width: '3 cm',
      colour: 'silver',
      gender: 'Women',
      totalweight: '37.4 g',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Gucci',
      rating: 5,
      numReviews: 14,
      description:
        'Gucci - silver bracelet very rare in a good condition. done magnetic cleaning and polishing total length approx 20cm',
    },
    {
      // _id: '8',
      name: 'Gucci - 925 Silver - Necklace',
      slug: 'Gucci 925 Silver Necklace',
      category: 'Necklace',
      image: '/images/p11.jpg',
      price: 190,
      size: 'One size',
      material: 'Silver',
      height: '10 cm',
      width: '3 cm',
      colour: 'silver',
      gender: 'Unisex',
      totalweight: '56  g',
      condition: 'Good condition - used with some signs of wear',
      countInStock: 1,
      brand: 'Gucci',
      rating: 4,
      numReviews: 18,
      description:
        'Gucci Double Dog Tag Ball Chain Necklace 925 Sterling Silver in very good condition magnetic cleaning done material - silver 925',
    },
    {
      // _id: '8',
      name: 'Hermès Bracelet Metal',
      slug: 'Hermès Bracelet #3',
      category: 'Bracelet',
      image: '/images/p12.jpg',
      price: 230,
      size: 'One size',
      material: 'Enamel, Metal',
      height: '1 cm',
      width: '6.5 cm',
      colour: 'Multicolour',
      gender: 'Unisex',
      totalweight: '61 g',
      condition: 'Very good condition, slightly used with small signs of wear',
      countInStock: 1,
      brand: 'Hermès',
      rating: 5,
      numReviews: 18,
      description:
        'Hermes goldtone enamel bangle bracelet narrow bracelet with ornaments and gold stripes on the sides very good condition inner diameter 6.5 cm material - metal enamel',
    },
  ],
};

export default data;
